### ISSUE TITLE
Bind configuration 

### ISSUE THREAD

**Issue by viniciusgava** [nicokaiser/Dyndns#12]
Hello, Could you give more detail how to configure the bind to work?

I create the named.conf.local with key and the zone in conf directory and add it to index.php config.

But this part I does not understand what I need to do:

```
In this case, the zone is also called "dyndns.example.com". The (initial) db.dyndns.example.com file (located in BIND's cache directory) looks like this:

$TTL 1h
@ IN SOA dyndns.example.com. root.example.com. (
        2007111501      ; serial
        1h              ; refresh
        15m             ; retry
        7d              ; expiration
        1h              ; minimum
        )  
        NS <your dns server>
Remember to change access rights so BIND is able to write to this file. On Ubuntu the zone need to be in /var/lib/bind due to AppArmor.
```

I have a ubuntu server.

**Comment by nicokaiser** [comment]
You need to create a file with the above contents (with the hostnames and settings adjusted to your needs) and add them to your BIND cache directory (on Ubuntu it might `/var/lib/bind/db.dyndns.example.com` in this case). This must also be referenced in the `named.conf.local` zone entry for your domain.
