### ISSUE TITLE
Possibility to add/delete user+passwords and domains in an admin interface

### ISSUE THREAD

**Issue by F1reF0x** [nicokaiser/Dyndns#2]
Hi, thanks for your dyndns project. Would it be possible to add a feature to add/delete/change users and their password and connected domains in an admin interface?

Thx,
FireFox

**Comment by nicokaiser** [comment]
Hi! Currently this is not planned, as I wanted to keep the module as simple as possible (and expose only the DNS updater API, not another UI for administration)... This way I can use a simple (even read-only) text file as "database". Sorry...
