### ISSUE TITLE
Use of ddclient

### ISSUE THREAD

**Issue by MaxChinni** [nicokaiser/Dyndns#4]
Hi,
  if you try to use ddclient (protocol dyndns2) to update your dynamic DNS, you can see that the requested URL is something like this

```
GET /nic/update?system=dyndns&hostname=yourhost.example.com&myip=1.2.3.4 HTTP/1.0
```

If you put on the web server the `index.php` page you gave in the `README.md`, it would be necessary to implement a rewrite rule like this in a `.htaccess` file

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /index.php [L]
```

Am I wrong?

I think it would be a good advice to have in the installation instructions.

Regards

**Comment by nicokaiser** [comment]
This looks good, though I did not test this. I think (!) ddclient can be configured so the request is not 

```
GET /nic/update?system=dyndns&hostname=yourhost.example.com&myip=1.2.3.4 HTTP/1.0
```

but

```
GET /index.php?hostname=yourhost.example.com&myip=1.2.3.4 HTTP/1.0
```

If you need DynDNS compatibility (with a URL like `/nic/update` you might need to configure the webserver for this (e.g. with a `.htaccess` for apache).

However this is not an issue but rather a documentation thing, I guess?

**Comment by MaxChinni** [comment]
It's definitively a documentation thing.

The `README.md` states that is possible to use the same syntax as the original DynDNS.org servers. I searched the [official Dyn API documentation](http://dyn.com/support/developers/api/perform-update/) and I found that the `/nic/update` URL is used to perform an update.

I used `ddclient` with a configuration quite similar to the one provided on the [dyn.com support pages](http://dyn.com/support/clients/linux/ddclient/) (`protocol=dyndns2`) and so I needed to do the Apache's `.htaccess` redirect thing.

**Comment by agomerz** [comment]
Were you able to get this working with ddclient?
I have tried the example ddclient.conf as outlined by DynDNS 
and am getting badauth.
It does not look like ddclient is using http basic auth...

**Comment by nicokaiser** [comment]
Ok, this seems to work with the "dyndns2" protocol, but you may have to set the "script" option in the ddclient.conf if you do not run the server on `/nic/update`:

```
protocol=dyndns2
use=if, if=ppp0
server=dyn.example.com
login=myusername
password='mypassword'
script=/
myhostname.dyn.example.com
```
