### ISSUE TITLE
mod_rewrite https not working

### ISSUE THREAD

**Issue by pheelee** [nicokaiser/Dyndns#8]
Hi Nico

First of all thank you very much for the great work!
I'm redirecting every request from http to https using mod_rewrite.
Do you know any issues using apaches mod_rewrite?

greets phil

**Comment by nicokaiser** [comment]
I did not test this but this should work as with http. Do you have any issues?

**Comment by pheelee** [comment]
yes it does work like http on the server side.
I'm sorry the client does not work as expected. It's a custom dyndns entry on my synology diskstation.
